name: Continuous Integration, Deployment
on:
  push:
    branches:
      - main
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Navigate to frontend
        working-directory: frontend
        run: echo "Navigating to frontend directory"
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Install Dependencies
        working-directory: frontend
        run: npm install
      
      - name: Build Project
        working-directory: frontend
        run: npm run build
        
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: frontend/dist

  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_CD_TOKEN }}
          publish_dir: ./dist
